### PR TITLE
Improve plotting output from grain segmentaion

### PR DESCRIPTION
**Pull request by dtorrejo**

### CODE REVIEW

**Comment by dtorrejo** [comment]
@wesleyktatum Look at jupyter notebook for reference on how to use the latest code

**Comment by dtorrejo** [comment]
@wesleyktatum I'm adding Anton's jupyter notebook. You may want to rename it and clear output in a future PR.

**Comment by dtorrejo** [comment]
@wesleyktatum I have removed several redundant files and directories. I'm using the new organization.

**Comment by dtorrejo** [comment]
@wesleyktatum Should we remove example.py? I'm not updating it anymore. I'm mostly updating the jupyter notebook. Let me know if you need it.

**Comment by wesleyktatum** [comment]
> @wesleyktatum I'm adding Anton's jupyter notebook. You may want to rename it and clear output in a future PR.

I've re-added this file to the .gitignore. I would prefer to keep my jupyter notebooks with lab data in the .gitignore, so I've added a few other .ipynb files to the .gitignor as well. Could you apply this as well?

> @wesleyktatum I have removed several redundant files and directories. I'm using the new organization.

Your file and import updates look good as well.




> @wesleyktatum Should we remove example.py? I'm not updating it anymore. I'm mostly updating the jupyter notebook. Let me know if you need it.

Let's turn the example.py into an example.ipynb, where we use markdown cells to walk new users through the different aspects of the workflow. This can be a future project, so let's just keep example.py for now?

**Pull request merged**
